#!/usr/bin/env python3
"""Writes GlassInk.kt: for each glass widget layout, which views change colour
when the widget look is dark and its text turns light.

Read from the layouts themselves, so a TextView added to one is covered
without anybody remembering to list it — and RemoteViews refuses to paint an
id that is not in the layout, so a hand-kept list that drifted would break
the widget, not just its colours.

  primary  TextViews in @color/widget_text, or with no colour set
  muted    TextViews in @color/widget_text_muted
  tinted   ImageViews showing a muted-tinted icon (the refresh arrow)

Anything with its own colour (the accent numbers, white text on the canvas
caption's dark scrim) is left alone.

Re-run after changing a layout:

    python3 widgets/android/tools/generate_ink.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ANDROID = os.path.join(HERE, '..')
LAYOUTS = os.path.join(ANDROID, 'res', 'layout')
TINTED_ICONS = {'@drawable/widget_refresh_icon'}


def scan(path):
    text = open(path, encoding='utf-8').read()
    primary, muted, tinted = [], [], []
    for m in re.finditer(r'<(TextView|ImageView)\b([^>]*)>', text):
        tag, attrs = m.groups()
        ident = re.search(r'android:id="@\+id/(\w+)"', attrs)
        if not ident:
            continue
        name = ident.group(1)
        if tag == 'TextView':
            color = re.search(r'android:textColor="([^"]+)"', attrs)
            color = color.group(1) if color else None
            if color in (None, '@color/widget_text'):
                primary.append(name)
            elif color == '@color/widget_text_muted':
                muted.append(name)
        else:
            src = re.search(r'android:src="([^"]+)"', attrs)
            if src and src.group(1) in TINTED_ICONS:
                tinted.append(name)
    return primary, muted, tinted


def ids(names):
    return ', '.join(f'R.id.{n}' for n in names)


def main():
    rows = []
    for name in sorted(os.listdir(LAYOUTS)):
        if not name.endswith('.xml'):
            continue
        text = open(os.path.join(LAYOUTS, name), encoding='utf-8').read()
        if '@+id/widget_bg' not in text:
            continue   # not a glass widget (the locket is the photo itself)
        primary, muted, tinted = scan(os.path.join(LAYOUTS, name))
        layout = name[:-4]
        rows.append(
            f'    R.layout.{layout} to GlassInk(\n'
            f'        primary = intArrayOf({ids(primary)}),\n'
            f'        muted = intArrayOf({ids(muted)}),\n'
            f'        tinted = intArrayOf({ids(tinted)})\n'
            f'    )'
        )
    body = ',\n'.join(rows)
    kt = f'''package com.loversrock.app.widgets

import com.loversrock.app.R

// GENERATED by widgets/android/tools/generate_ink.py from the layouts — edit
// that, not this.

/** The views in one layout that follow the text colour of the widget look. */
internal class GlassInk(val primary: IntArray, val muted: IntArray, val tinted: IntArray)

internal val GLASS_INK: Map<Int, GlassInk> = mapOf(
{body}
)
'''
    with open(os.path.join(ANDROID, 'GlassInk.kt'), 'w') as f:
        f.write(kt)
    print(f'{len(rows)} layouts')


if __name__ == '__main__':
    main()
