#!/usr/bin/env python3
"""Writes res/drawable/widget_distance_wiggle.xml: the wiggly dotted line that
joins the two of you on the distance widget.

A vector of dots rather than a dashed stroke, because a VectorDrawable has no
dash pattern at all — and a dotted line is what was asked for anyway. Each dot
is its own tiny circle, placed along a sine wave by ARC LENGTH, not by x, so
they are evenly spaced along the curve instead of bunching on the slopes.

The layout shows it with scaleType="centerCrop" inside a strip exactly as tall
as the drawable, so it is never stretched (the dots stay round) and the
widget just shows more or less of it as it is resized. It is symmetric about
the middle, where the heart sits, so whatever is cropped off comes off both
ends equally.

Re-run after changing the numbers:

    python3 widgets/android/tools/generate_wiggle.py
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'res', 'drawable', 'widget_distance_wiggle.xml')

WIDTH = 480        # dp — wider than any 4-cell widget, so it always fills
HEIGHT = 24        # dp — the strip it sits in is this tall
AMPLITUDE = 6.5    # dp either side of the middle
WAVELENGTH = 56    # dp per full wiggle
SPACING = 6.5      # dp between dot centres, along the curve
RADIUS = 1.6       # dp


def y(x):
    # Crosses the middle at the centre, so the heart sits on the line.
    return HEIGHT / 2 + AMPLITUDE * math.sin(2 * math.pi * (x - WIDTH / 2) / WAVELENGTH)


def walk(direction):
    """Dot centres from the middle outwards, one direction."""
    out, x, travelled, step = [], WIDTH / 2, 0.0, 0.05
    px, py = x, y(x)
    while RADIUS <= x <= WIDTH - RADIUS:
        x += direction * step
        nx, ny = x, y(x)
        travelled += math.hypot(nx - px, ny - py)
        px, py = nx, ny
        if travelled >= SPACING:
            out.append((nx, ny))
            travelled -= SPACING
    return out


def dot(cx, cy):
    r = RADIUS
    return (f'M{cx - r:.2f},{cy:.2f}a{r},{r} 0 1,0 {2 * r},0'
            f'a{r},{r} 0 1,0 {-2 * r},0z')


def main():
    # No dot exactly in the middle: the heart covers it.
    points = list(reversed(walk(-1))) + walk(1)
    path = ''.join(dot(cx, cy) for cx, cy in points)
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by widgets/android/tools/generate_wiggle.py — edit that, not this.
     The wiggly dotted line between the two of you on the distance widget. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{WIDTH}dp"
    android:height="{HEIGHT}dp"
    android:viewportWidth="{WIDTH}"
    android:viewportHeight="{HEIGHT}">
    <path
        android:fillColor="@color/widget_accent"
        android:fillAlpha="0.75"
        android:pathData="{path}" />
</vector>
'''
    with open(OUT, 'w') as f:
        f.write(xml)
    print(f'{len(points)} dots -> {os.path.relpath(OUT)}')


if __name__ == '__main__':
    main()
