#!/usr/bin/env python3
"""Writes the grey glass widget backgrounds, one per translucency level.

A widget cannot be handed an opacity at runtime: RemoteViews only lets the
app swap which drawable a view uses. So every level the Settings slider can
reach exists here as its own drawable, and the widget picks one
(GlassStyle.kt). Everything is generated from this one file so the levels
cannot drift apart:

    res/drawable/widget_glass_NN.xml   one per level, NN = percent opaque
    res/drawable/widget_background.xml the default level, which the layouts
                                       name so a widget looks right before
                                       its first paint
    GlassLevels.kt                     the level -> drawable table

Re-run after changing anything here:

    python3 widgets/android/tools/generate_glass.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ANDROID = os.path.join(HERE, '..')
DRAWABLE = os.path.join(ANDROID, 'res', 'drawable')

LEVELS = list(range(20, 101, 5))   # percent opaque; must match the app's slider
DEFAULT = 70                        # must match DEFAULT_WIDGET_OPACITY in the app
TOP_RGB = 'E4E6EA'                  # a shade lighter at the top …
BOTTOM_RGB = 'AEB2BA'               # … than the bottom
SPREAD = 3                          # percent either side of the level


def alpha(percent):
    return '%02X' % round(255 * max(0, min(100, percent)) / 100)


def drawable(level, note):
    top = alpha(level + SPREAD)
    bottom = alpha(level - SPREAD)
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by widgets/android/tools/generate_glass.py — edit that, not this.
     {note}

     Grey liquid glass at {level}% opaque. A launcher will not blur the
     wallpaper behind an app's widget, so the glass is built from what it
     can do: a translucent grey body (a shade lighter at the top), a sheen
     across the upper half, and a bright hairline rim. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <gradient
                android:angle="270"
                android:startColor="#{top}{TOP_RGB}"
                android:endColor="#{bottom}{BOTTOM_RGB}" />
            <corners android:radius="24dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <gradient
                android:angle="270"
                android:startColor="@color/widget_glass_sheen"
                android:centerColor="#00FFFFFF"
                android:centerY="0.45"
                android:endColor="#00FFFFFF" />
            <corners android:radius="24dp" />
        </shape>
    </item>
    <item>
        <shape android:shape="rectangle">
            <solid android:color="#00000000" />
            <stroke android:width="1dp" android:color="@color/widget_glass_rim" />
            <corners android:radius="24dp" />
        </shape>
    </item>
</layer-list>
'''


def main():
    for level in LEVELS:
        with open(os.path.join(DRAWABLE, f'widget_glass_{level}.xml'), 'w') as f:
            f.write(drawable(level, 'One step of the widget translucency slider in Settings.'))
    with open(os.path.join(DRAWABLE, 'widget_background.xml'), 'w') as f:
        f.write(drawable(DEFAULT, 'The background of EVERY loversrock widget but the locket, at the\n'
                                  '     default level. GlassStyle swaps in the level chosen in Settings.'))
    rows = ',\n'.join(f'    {level} to R.drawable.widget_glass_{level}' for level in LEVELS)
    kt = f'''package com.loversrock.app.widgets

import com.loversrock.app.R

// GENERATED by widgets/android/tools/generate_glass.py — edit that, not this.

/** Percent opaque -> the glass drawable drawn at that level. */
internal val GLASS_LEVELS: List<Pair<Int, Int>> = listOf(
{rows}
)

internal const val GLASS_DEFAULT = {DEFAULT}
'''
    with open(os.path.join(ANDROID, 'GlassLevels.kt'), 'w') as f:
        f.write(kt)
    print(f'{len(LEVELS)} levels, default {DEFAULT}%')


if __name__ == '__main__':
    main()
