"""Emits a Kotlin `R` object mirroring what aapt would generate from
widgets/android/res, so the type-check resolves the same symbols the real
build will. Run from mobile/ via typecheck.sh."""
import sys, re, os, glob, collections

out = sys.argv[1]
res = 'widgets/android/res'
buckets = collections.defaultdict(set)

for path in glob.glob(f'{res}/**/*', recursive=True):
    if not os.path.isfile(path):
        continue
    kind = os.path.basename(os.path.dirname(path))
    name = os.path.splitext(os.path.basename(path))[0]
    if kind in ('layout', 'drawable', 'xml'):
        buckets[kind].add(name)
    if kind == 'values':
        text = open(path, encoding='utf-8').read()
        for m in re.finditer(r'<(color|string|dimen)\s+name="([^"]+)"', text):
            buckets[m.group(1)].add(m.group(2))

# Ids are declared inline by the layouts as @+id/foo.
for path in glob.glob(f'{res}/layout/*.xml'):
    for m in re.finditer(r'"@\+id/([\w.]+)"', open(path, encoding='utf-8').read()):
        buckets['id'].add(m.group(1))

lines = ['package com.loversrock.app', '',
         '// GENERATED by tools/generate_r_stub.py — do not edit.', 'object R {']
for kind in sorted(buckets):
    lines.append(f'    object {kind} {{')
    for name in sorted(buckets[kind]):
        lines.append(f'        const val {name} = 0')
    lines.append('    }')
lines.append('}')
open(out, 'w').write('\n'.join(lines) + '\n')
print(f"  R stub: {sum(len(v) for v in buckets.values())} symbols "
      f"({', '.join(f'{k}={len(v)}' for k, v in sorted(buckets.items()))})")
