import { NativeModules, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { apiFetch, getApiUrl } from './api';

// The native module only exists in a dev-client/EAS build that ran
// `expo prebuild` with the widget config plugins. In Expo Go it is simply
// absent, so every call here degrades to a no-op rather than throwing — the
// app must stay fully usable without widgets.
const native = NativeModules.WidgetBridge || null;

export const widgetsSupported = native !== null;

// Android phones have no lock screen widget API (removed in Android 5.0,
// tablet-only since Android 15). There we fall back to an ongoing
// notification; iOS gets real WidgetKit lock screen widgets.
export const lockScreenStyle = Platform.OS === 'ios' ? 'widget' : 'notification';

/**
 * Issues a fresh scoped widget token and hands it to the native side. Safe to
 * call on every login — old tokens stay listed and individually revocable.
 */
export async function provisionWidgets() {
  if (!native) return { provisioned: false, reason: 'Widgets need a dev-client build' };

  try {
    const { widgetToken } = await apiFetch('/widget/token', {
      method: 'POST',
      body: { label: `${Platform.OS} device` },
    });
    // Read at call time: the server address is changeable in Settings, and
    // the widget process needs whatever it is now, not the build-time value.
    await native.setCredentials(getApiUrl(), widgetToken);
    // Re-send the chosen translucency too: a fresh install, or a widget
    // store wiped some other way, should still wear the glass you picked.
    pushWidgetOpacity(await getWidgetOpacity());
    return { provisioned: true };
  } catch (err) {
    return { provisioned: false, reason: err.message };
  }
}

/** Called on logout/unlink so a widget can't keep showing the old couple's data. */
export async function clearWidgets() {
  if (!native) return;
  try {
    await native.clearCredentials();
  } catch {
    // Nothing actionable — the widget will fail its next fetch and blank out.
  }
}

export async function refreshWidgets() {
  if (!native) return;
  try {
    await native.refresh();
  } catch {}
}

// ------------------------------------------------------------ translucency

/**
 * How see-through the widgets' grey glass is, in percent opaque. The range
 * and steps match the drawables Android has for it (one per 5%, generated by
 * widgets/android/tools/generate_glass.py) — a value between steps would
 * just snap to the nearest one.
 */
export const WIDGET_OPACITY = { min: 20, max: 100, step: 5, default: 70 };
const OPACITY_KEY = 'loversrock.widgetOpacity';

const clampOpacity = (n) => {
  const { min, max, step } = WIDGET_OPACITY;
  const v = Number.isFinite(n) ? n : WIDGET_OPACITY.default;
  return Math.min(max, Math.max(min, Math.round(v / step) * step));
};

export async function getWidgetOpacity() {
  try {
    const raw = await AsyncStorage.getItem(OPACITY_KEY);
    return raw == null ? WIDGET_OPACITY.default : clampOpacity(Number(raw));
  } catch {
    return WIDGET_OPACITY.default;
  }
}

function pushWidgetOpacity(percent) {
  // Guarded by name as well: an older build has the bridge but not this.
  if (!native || typeof native.setWidgetOpacity !== 'function') return Promise.resolve();
  return native.setWidgetOpacity(percent).catch(() => {});
}

/** Remembers the level and repaints every widget with it. */
export async function setWidgetOpacity(percent) {
  const value = clampOpacity(percent);
  try { await AsyncStorage.setItem(OPACITY_KEY, String(value)); } catch {}
  await pushWidgetOpacity(value);
  return value;
}

export async function setLockScreenEnabled(enabled) {
  if (!native) return;
  try {
    await native.setLockScreenEnabled(enabled);
  } catch {}
}
