package com.loversrock.app.widgets

import com.loversrock.app.R

// GENERATED by widgets/android/tools/generate_glass.py — edit that, not this.

/** Percent opaque -> the glass drawable drawn at that level. */
internal val GLASS_LEVELS: List<Pair<Int, Int>> = listOf(
    20 to R.drawable.widget_glass_20,
    25 to R.drawable.widget_glass_25,
    30 to R.drawable.widget_glass_30,
    35 to R.drawable.widget_glass_35,
    40 to R.drawable.widget_glass_40,
    45 to R.drawable.widget_glass_45,
    50 to R.drawable.widget_glass_50,
    55 to R.drawable.widget_glass_55,
    60 to R.drawable.widget_glass_60,
    65 to R.drawable.widget_glass_65,
    70 to R.drawable.widget_glass_70,
    75 to R.drawable.widget_glass_75,
    80 to R.drawable.widget_glass_80,
    85 to R.drawable.widget_glass_85,
    90 to R.drawable.widget_glass_90,
    95 to R.drawable.widget_glass_95,
    100 to R.drawable.widget_glass_100
)

internal const val GLASS_DEFAULT = 70
