package com.loversrock.app.widgets

import com.loversrock.app.R

// GENERATED by widgets/android/tools/generate_ink.py from the layouts — edit
// that, not this.

/** The views in one layout that follow the text colour of the widget look. */
internal class GlassInk(val primary: IntArray, val muted: IntArray, val tinted: IntArray)

internal val GLASS_INK: Map<Int, GlassInk> = mapOf(
    R.layout.widget_canvas to GlassInk(
        primary = intArrayOf(R.id.glance_label),
        muted = intArrayOf(R.id.glance_caption),
        tinted = intArrayOf()
    ),
    R.layout.widget_distance to GlassInk(
        primary = intArrayOf(R.id.glance_value, R.id.distance_left_mood, R.id.distance_left_symptoms, R.id.distance_right_mood, R.id.distance_right_symptoms),
        muted = intArrayOf(R.id.glance_label, R.id.glance_caption),
        tinted = intArrayOf(R.id.widget_refresh)
    ),
    R.layout.widget_glance to GlassInk(
        primary = intArrayOf(R.id.glance_value),
        muted = intArrayOf(R.id.glance_label, R.id.glance_caption),
        tinted = intArrayOf(R.id.widget_refresh)
    ),
    R.layout.widget_kiss to GlassInk(
        primary = intArrayOf(R.id.glance_value, R.id.glance_label),
        muted = intArrayOf(R.id.glance_caption),
        tinted = intArrayOf()
    ),
    R.layout.widget_summary to GlassInk(
        primary = intArrayOf(R.id.widget_headline),
        muted = intArrayOf(R.id.widget_subline, R.id.widget_countdown_label, R.id.widget_distance_label),
        tinted = intArrayOf(R.id.widget_refresh)
    )
)
