// Made by scripts/build-sky.py: do not edit by hand, run it again.
//
// SKY_FRAMES are the pictures of the day, each its own mix of lights:
// for each scene, its sky and its foreground under it.
// SKY_TIMELINE is [hour, picture, stars] through the day: between two
// rows the sky blends from one picture to the next.
/* eslint-disable global-require */
export const SKY_FRAMES = [
  {
    goldengate: { sky: require('../assets/sky/goldengate/00-sky.jpg'), ground: require('../assets/sky/goldengate/00-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/00-sky.jpg'), ground: require('../assets/sky/newyork/00-ground.webp') },
    mix: { night: 0.15, moon: 0.85 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/01-sky.jpg'), ground: require('../assets/sky/goldengate/01-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/01-sky.jpg'), ground: require('../assets/sky/newyork/01-ground.webp') },
    mix: { night: 0.127, moon: 0.873 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/02-sky.jpg'), ground: require('../assets/sky/goldengate/02-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/02-sky.jpg'), ground: require('../assets/sky/newyork/02-ground.webp') },
    mix: { night: 0.075, moon: 0.925 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/03-sky.jpg'), ground: require('../assets/sky/goldengate/03-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/03-sky.jpg'), ground: require('../assets/sky/newyork/03-ground.webp') },
    mix: { night: 0.023, moon: 0.977 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/04-sky.jpg'), ground: require('../assets/sky/goldengate/04-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/04-sky.jpg'), ground: require('../assets/sky/newyork/04-ground.webp') },
    mix: { moon: 1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/05-sky.jpg'), ground: require('../assets/sky/goldengate/05-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/05-sky.jpg'), ground: require('../assets/sky/newyork/05-ground.webp') },
    mix: { night: 0.039, moon: 0.961 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/06-sky.jpg'), ground: require('../assets/sky/goldengate/06-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/06-sky.jpg'), ground: require('../assets/sky/newyork/06-ground.webp') },
    mix: { night: 0.125, moon: 0.875 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/07-sky.jpg'), ground: require('../assets/sky/goldengate/07-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/07-sky.jpg'), ground: require('../assets/sky/newyork/07-ground.webp') },
    mix: { night: 0.211, moon: 0.789 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/08-sky.jpg'), ground: require('../assets/sky/goldengate/08-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/08-sky.jpg'), ground: require('../assets/sky/newyork/08-ground.webp') },
    mix: { night: 0.25, moon: 0.75 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/09-sky.jpg'), ground: require('../assets/sky/goldengate/09-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/09-sky.jpg'), ground: require('../assets/sky/newyork/09-ground.webp') },
    mix: { night: 0.341, moon: 0.659 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/10-sky.jpg'), ground: require('../assets/sky/goldengate/10-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/10-sky.jpg'), ground: require('../assets/sky/newyork/10-ground.webp') },
    mix: { night: 0.509, moon: 0.491 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/11-sky.jpg'), ground: require('../assets/sky/goldengate/11-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/11-sky.jpg'), ground: require('../assets/sky/newyork/11-ground.webp') },
    mix: { night: 0.6, moon: 0.4 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/12-sky.jpg'), ground: require('../assets/sky/goldengate/12-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/12-sky.jpg'), ground: require('../assets/sky/newyork/12-ground.webp') },
    mix: { night: 0.704, moon: 0.296 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/13-sky.jpg'), ground: require('../assets/sky/goldengate/13-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/13-sky.jpg'), ground: require('../assets/sky/newyork/13-ground.webp') },
    mix: { night: 0.896, moon: 0.104 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/14-sky.jpg'), ground: require('../assets/sky/goldengate/14-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/14-sky.jpg'), ground: require('../assets/sky/newyork/14-ground.webp') },
    mix: { night: 1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/15-sky.jpg'), ground: require('../assets/sky/goldengate/15-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/15-sky.jpg'), ground: require('../assets/sky/newyork/15-ground.webp') },
    mix: { twilight: 0.225, night: 0.775 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/16-sky.jpg'), ground: require('../assets/sky/goldengate/16-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/16-sky.jpg'), ground: require('../assets/sky/newyork/16-ground.webp') },
    mix: { twilight: 0.45, night: 0.55 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/17-sky.jpg'), ground: require('../assets/sky/goldengate/17-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/17-sky.jpg'), ground: require('../assets/sky/newyork/17-ground.webp') },
    mix: { dawn: 0.25, twilight: 0.475, night: 0.275 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/18-sky.jpg'), ground: require('../assets/sky/goldengate/18-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/18-sky.jpg'), ground: require('../assets/sky/newyork/18-ground.webp') },
    mix: { dawn: 0.5, twilight: 0.5 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/19-sky.jpg'), ground: require('../assets/sky/goldengate/19-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/19-sky.jpg'), ground: require('../assets/sky/newyork/19-ground.webp') },
    mix: { dawn: 0.75, twilight: 0.25 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/20-sky.jpg'), ground: require('../assets/sky/goldengate/20-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/20-sky.jpg'), ground: require('../assets/sky/newyork/20-ground.webp') },
    mix: { dawn: 1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/21-sky.jpg'), ground: require('../assets/sky/goldengate/21-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/21-sky.jpg'), ground: require('../assets/sky/newyork/21-ground.webp') },
    mix: { dawn: 0.875, day: 0.125 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/22-sky.jpg'), ground: require('../assets/sky/goldengate/22-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/22-sky.jpg'), ground: require('../assets/sky/newyork/22-ground.webp') },
    mix: { dawn: 0.75, day: 0.25 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/23-sky.jpg'), ground: require('../assets/sky/goldengate/23-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/23-sky.jpg'), ground: require('../assets/sky/newyork/23-ground.webp') },
    mix: { dawn: 0.646, day: 0.354 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/24-sky.jpg'), ground: require('../assets/sky/goldengate/24-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/24-sky.jpg'), ground: require('../assets/sky/newyork/24-ground.webp') },
    mix: { dawn: 0.454, day: 0.546 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/25-sky.jpg'), ground: require('../assets/sky/goldengate/25-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/25-sky.jpg'), ground: require('../assets/sky/newyork/25-ground.webp') },
    mix: { dawn: 0.35, day: 0.65 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/26-sky.jpg'), ground: require('../assets/sky/goldengate/26-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/26-sky.jpg'), ground: require('../assets/sky/newyork/26-ground.webp') },
    mix: { dawn: 0.311, day: 0.689 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/27-sky.jpg'), ground: require('../assets/sky/goldengate/27-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/27-sky.jpg'), ground: require('../assets/sky/newyork/27-ground.webp') },
    mix: { dawn: 0.225, day: 0.775 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/28-sky.jpg'), ground: require('../assets/sky/goldengate/28-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/28-sky.jpg'), ground: require('../assets/sky/newyork/28-ground.webp') },
    mix: { dawn: 0.139, day: 0.861 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/29-sky.jpg'), ground: require('../assets/sky/goldengate/29-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/29-sky.jpg'), ground: require('../assets/sky/newyork/29-ground.webp') },
    mix: { dawn: 0.1, day: 0.9 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/30-sky.jpg'), ground: require('../assets/sky/goldengate/30-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/30-sky.jpg'), ground: require('../assets/sky/newyork/30-ground.webp') },
    mix: { dawn: 0.094, day: 0.906 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/31-sky.jpg'), ground: require('../assets/sky/goldengate/31-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/31-sky.jpg'), ground: require('../assets/sky/newyork/31-ground.webp') },
    mix: { dawn: 0.08, day: 0.92 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/32-sky.jpg'), ground: require('../assets/sky/goldengate/32-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/32-sky.jpg'), ground: require('../assets/sky/newyork/32-ground.webp') },
    mix: { dawn: 0.061, day: 0.939 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/33-sky.jpg'), ground: require('../assets/sky/goldengate/33-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/33-sky.jpg'), ground: require('../assets/sky/newyork/33-ground.webp') },
    mix: { dawn: 0.039, day: 0.961 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/34-sky.jpg'), ground: require('../assets/sky/goldengate/34-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/34-sky.jpg'), ground: require('../assets/sky/newyork/34-ground.webp') },
    mix: { dawn: 0.02, day: 0.98 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/35-sky.jpg'), ground: require('../assets/sky/goldengate/35-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/35-sky.jpg'), ground: require('../assets/sky/newyork/35-ground.webp') },
    mix: { dawn: 0.006, day: 0.994 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/36-sky.jpg'), ground: require('../assets/sky/goldengate/36-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/36-sky.jpg'), ground: require('../assets/sky/newyork/36-ground.webp') },
    mix: { day: 1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/37-sky.jpg'), ground: require('../assets/sky/goldengate/37-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/37-sky.jpg'), ground: require('../assets/sky/newyork/37-ground.webp') },
    mix: { day: 0.988, golden: 0.012 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/38-sky.jpg'), ground: require('../assets/sky/goldengate/38-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/38-sky.jpg'), ground: require('../assets/sky/newyork/38-ground.webp') },
    mix: { day: 0.96, golden: 0.04 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/39-sky.jpg'), ground: require('../assets/sky/goldengate/39-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/39-sky.jpg'), ground: require('../assets/sky/newyork/39-ground.webp') },
    mix: { day: 0.933, golden: 0.067 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/40-sky.jpg'), ground: require('../assets/sky/goldengate/40-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/40-sky.jpg'), ground: require('../assets/sky/newyork/40-ground.webp') },
    mix: { day: 0.92, golden: 0.08 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/41-sky.jpg'), ground: require('../assets/sky/goldengate/41-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/41-sky.jpg'), ground: require('../assets/sky/newyork/41-ground.webp') },
    mix: { day: 0.893, golden: 0.107 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/42-sky.jpg'), ground: require('../assets/sky/goldengate/42-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/42-sky.jpg'), ground: require('../assets/sky/newyork/42-ground.webp') },
    mix: { day: 0.835, golden: 0.165 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/43-sky.jpg'), ground: require('../assets/sky/goldengate/43-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/43-sky.jpg'), ground: require('../assets/sky/newyork/43-ground.webp') },
    mix: { day: 0.777, golden: 0.223 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/44-sky.jpg'), ground: require('../assets/sky/goldengate/44-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/44-sky.jpg'), ground: require('../assets/sky/newyork/44-ground.webp') },
    mix: { day: 0.75, golden: 0.25 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/45-sky.jpg'), ground: require('../assets/sky/goldengate/45-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/45-sky.jpg'), ground: require('../assets/sky/newyork/45-ground.webp') },
    mix: { day: 0.695, golden: 0.305 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/46-sky.jpg'), ground: require('../assets/sky/goldengate/46-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/46-sky.jpg'), ground: require('../assets/sky/newyork/46-ground.webp') },
    mix: { day: 0.575, golden: 0.425 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/47-sky.jpg'), ground: require('../assets/sky/goldengate/47-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/47-sky.jpg'), ground: require('../assets/sky/newyork/47-ground.webp') },
    mix: { day: 0.455, golden: 0.545 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/48-sky.jpg'), ground: require('../assets/sky/goldengate/48-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/48-sky.jpg'), ground: require('../assets/sky/newyork/48-ground.webp') },
    mix: { day: 0.4, golden: 0.6 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/49-sky.jpg'), ground: require('../assets/sky/goldengate/49-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/49-sky.jpg'), ground: require('../assets/sky/newyork/49-ground.webp') },
    mix: { day: 0.296, golden: 0.639, sunset: 0.065 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/50-sky.jpg'), ground: require('../assets/sky/goldengate/50-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/50-sky.jpg'), ground: require('../assets/sky/newyork/50-ground.webp') },
    mix: { day: 0.104, golden: 0.711, sunset: 0.185 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/51-sky.jpg'), ground: require('../assets/sky/goldengate/51-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/51-sky.jpg'), ground: require('../assets/sky/newyork/51-ground.webp') },
    mix: { golden: 0.75, sunset: 0.25 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/52-sky.jpg'), ground: require('../assets/sky/goldengate/52-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/52-sky.jpg'), ground: require('../assets/sky/newyork/52-ground.webp') },
    mix: { golden: 0.55, sunset: 0.45 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/53-sky.jpg'), ground: require('../assets/sky/goldengate/53-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/53-sky.jpg'), ground: require('../assets/sky/newyork/53-ground.webp') },
    mix: { golden: 0.35, sunset: 0.65 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/54-sky.jpg'), ground: require('../assets/sky/goldengate/54-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/54-sky.jpg'), ground: require('../assets/sky/newyork/54-ground.webp') },
    mix: { golden: 0.175, sunset: 0.825 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/55-sky.jpg'), ground: require('../assets/sky/goldengate/55-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/55-sky.jpg'), ground: require('../assets/sky/newyork/55-ground.webp') },
    mix: { sunset: 1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/56-sky.jpg'), ground: require('../assets/sky/goldengate/56-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/56-sky.jpg'), ground: require('../assets/sky/newyork/56-ground.webp') },
    mix: { sunset: 0.9, twilight: 0.1 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/57-sky.jpg'), ground: require('../assets/sky/goldengate/57-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/57-sky.jpg'), ground: require('../assets/sky/newyork/57-ground.webp') },
    mix: { sunset: 0.675, twilight: 0.325 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/58-sky.jpg'), ground: require('../assets/sky/goldengate/58-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/58-sky.jpg'), ground: require('../assets/sky/newyork/58-ground.webp') },
    mix: { sunset: 0.45, twilight: 0.55 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/59-sky.jpg'), ground: require('../assets/sky/goldengate/59-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/59-sky.jpg'), ground: require('../assets/sky/newyork/59-ground.webp') },
    mix: { sunset: 0.225, twilight: 0.65, night: 0.125 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/60-sky.jpg'), ground: require('../assets/sky/goldengate/60-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/60-sky.jpg'), ground: require('../assets/sky/newyork/60-ground.webp') },
    mix: { twilight: 0.75, night: 0.25 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/61-sky.jpg'), ground: require('../assets/sky/goldengate/61-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/61-sky.jpg'), ground: require('../assets/sky/newyork/61-ground.webp') },
    mix: { twilight: 0.525, night: 0.475 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/62-sky.jpg'), ground: require('../assets/sky/goldengate/62-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/62-sky.jpg'), ground: require('../assets/sky/newyork/62-ground.webp') },
    mix: { twilight: 0.3, night: 0.7 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/63-sky.jpg'), ground: require('../assets/sky/goldengate/63-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/63-sky.jpg'), ground: require('../assets/sky/newyork/63-ground.webp') },
    mix: { twilight: 0.15, night: 0.85 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/64-sky.jpg'), ground: require('../assets/sky/goldengate/64-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/64-sky.jpg'), ground: require('../assets/sky/newyork/64-ground.webp') },
    mix: { night: 0.961, moon: 0.039 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/65-sky.jpg'), ground: require('../assets/sky/goldengate/65-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/65-sky.jpg'), ground: require('../assets/sky/newyork/65-ground.webp') },
    mix: { night: 0.889, moon: 0.111 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/66-sky.jpg'), ground: require('../assets/sky/goldengate/66-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/66-sky.jpg'), ground: require('../assets/sky/newyork/66-ground.webp') },
    mix: { night: 0.85, moon: 0.15 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/67-sky.jpg'), ground: require('../assets/sky/goldengate/67-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/67-sky.jpg'), ground: require('../assets/sky/newyork/67-ground.webp') },
    mix: { night: 0.746, moon: 0.254 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/68-sky.jpg'), ground: require('../assets/sky/goldengate/68-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/68-sky.jpg'), ground: require('../assets/sky/newyork/68-ground.webp') },
    mix: { night: 0.554, moon: 0.446 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/69-sky.jpg'), ground: require('../assets/sky/goldengate/69-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/69-sky.jpg'), ground: require('../assets/sky/newyork/69-ground.webp') },
    mix: { night: 0.45, moon: 0.55 },
  },
  {
    goldengate: { sky: require('../assets/sky/goldengate/70-sky.jpg'), ground: require('../assets/sky/goldengate/70-ground.webp') },
    newyork: { sky: require('../assets/sky/newyork/70-sky.jpg'), ground: require('../assets/sky/newyork/70-ground.webp') },
    mix: { night: 0.3, moon: 0.7 },
  },
];

export const SKY_TIMELINE = [
  [0, 0, 0.8],
  [0.3333, 1, 0.792],
  [0.6667, 2, 0.775],
  [1, 3, 0.758],
  [1.3333, 4, 0.75],
  [1.6667, 5, 0.758],
  [2, 6, 0.775],
  [2.3333, 7, 0.792],
  [2.6667, 8, 0.8],
  [3, 9, 0.826],
  [3.3333, 10, 0.874],
  [3.6667, 11, 0.9],
  [4, 12, 0.926],
  [4.3333, 13, 0.974],
  [4.6667, 14, 1],
  [5, 15, 0.85],
  [5.3333, 16, 0.7],
  [5.6667, 17, 0.5],
  [6, 18, 0.3],
  [6.3333, 19, 0.15],
  [6.6667, 20, 0],
  [7, 21, 0],
  [7.3333, 22, 0],
  [7.6667, 23, 0],
  [8, 24, 0],
  [8.3333, 25, 0],
  [8.6667, 26, 0],
  [9, 27, 0],
  [9.3333, 28, 0],
  [9.6667, 29, 0],
  [10, 30, 0],
  [10.3333, 31, 0],
  [10.6667, 32, 0],
  [11, 33, 0],
  [11.3333, 34, 0],
  [11.6667, 35, 0],
  [12, 36, 0],
  [12.3333, 37, 0],
  [12.6667, 38, 0],
  [13, 39, 0],
  [13.3333, 40, 0],
  [13.6667, 41, 0],
  [14, 42, 0],
  [14.3333, 43, 0],
  [14.6667, 44, 0],
  [15, 45, 0],
  [15.3333, 46, 0],
  [15.6667, 47, 0],
  [16, 48, 0],
  [16.3333, 49, 0],
  [16.6667, 50, 0],
  [17, 51, 0],
  [17.3333, 52, 0],
  [17.6667, 53, 0],
  [18, 54, 0],
  [18.3333, 55, 0],
  [18.6667, 56, 0.05],
  [19, 57, 0.1],
  [19.3333, 58, 0.15],
  [19.6667, 59, 0.3],
  [20, 60, 0.45],
  [20.3333, 61, 0.625],
  [20.6667, 62, 0.8],
  [21, 63, 0.9],
  [21.3333, 14, 1],
  [21.6667, 64, 0.987],
  [22, 65, 0.963],
  [22.3333, 66, 0.95],
  [22.6667, 67, 0.924],
  [23, 68, 0.876],
  [23.3333, 69, 0.85],
  [23.6667, 70, 0.825],
  [24, 0, 0.8],
];
